apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: django-volume-mount
              mountPath: /usr/share/nginx/html
      volumes:
        - name: django-volume-mount
          persistentVolumeClaim:
            claimName: django-pvc