apiVersion: batch/v1
kind: Job
metadata:
  name: django-collectstatic
spec:
  template:
    spec:
      containers:
        - name: django
          image: minev/stepik:0.0.13
          command: ['python', 'manage.py', 'collectstatic', '--noinput']
          env:
            - name: DB_NAME
              value: stepik_db
            - name: DB_HOST
              value: mariadb-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key
          volumeMounts:
            - name: django-volume-mount
              mountPath: /opt/stepik/public
      volumes:
        - name: django-volume-mount
          persistentVolumeClaim:
            claimName: django-pvc
      restartPolicy: Never
  backoffLimit: 5