kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: django-pv